# Generated by Django 6.0.1 on 2026-04-29 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admission_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("r2", models.FloatField()),
                ("mse", models.FloatField()),
                ("mae", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
