# Generated by Django 6.0.1 on 2026-04-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gre", models.FloatField()),
                ("toefl", models.FloatField()),
                ("cgpa", models.FloatField()),
                ("sop", models.FloatField()),
                ("lor", models.FloatField()),
                ("research", models.IntegerField()),
                ("chance", models.FloatField()),
            ],
        ),
    ]
